### ISSUE TITLE
Failed to enable TOTP (new func)

### ISSUE THREAD

**Issue by termuxhackers-id** [suphiyasin/instagram-api#1]
I using **python3** with your new func for enable 2 factor.
```bash
GET TOTP CODE: 
{
"totp_seed":"MYYQQMO3R2PCAABSK4JIKJSHKGU266SM",
    "totp_seed_id":17953438667740618,
    "status":"ok"
}

PARAMS DATA:
{
    "verification_code":"406162",
    "_uid":"52301356617",
    "_uuid":"8bd64721-c95c-4849-883a-1a6a7868d5a3",
    "device_id":"android-7c9de4cd0c3c4344"
}

ENABLE TOPT:
{
    "message":"",
    "status":"fail"
}
```
Hope you can help me, **thanks** 🙏🏻

**Comment by suphiyasin** [comment]
New devices cannot make risky transactions on the account for 14/30 days, it is restricted by Instagram.

**Comment by termuxhackers-id** [comment]
> New devices cannot make risky transactions on the account for 14/30 days, it is restricted by Instagram.

Thank you for answering, there is no other way, right?

**Comment by suphiyasin** [comment]
You can add a Facebook account and activate it from there (This API is not available either).
If you have any other problems, you can open a ticket again. Have a nice day. <3

**Comment by Rahmataa** [comment]
I need instahack tool free please key 🔐  my wife old account open me please

**Comment by suphiyasin** [comment]
> I need instahack tool free please key 🔐  my wife old account open me please 

Contact with me via telegram
@suphi007
