### ISSUE TITLE
direct Message

### ISSUE THREAD

**Issue by ostore-irani** [suphiyasin/instagram-api#3]
hi

How to direct everyone?
by numerical ID
I want to send direct messages to other people with some fake accounts and advertise my page.

$api->user->sendMessage();

You can only send direct messages to your followers with this function

**Comment by suphiyasin** [comment]
Currently, this function is only available in the API.
I tested it and it worked with the same function when sending a message to a page I don't follow.

**Comment by ostore-irani** [comment]
Yes, I also tested it and it worked
But it works for sending a message (to the desired follower).
It does not send anything to the second message.
For example:
First message: Hello
Second message: I can design a website for you.

.
.
.
It is a great program, thank you

**Comment by suphiyasin** [comment]
I'm glad it was useful to you. I will soon add functions to send messages to people you do not follow in webapi. I'm working on the TikTok API these days, so I haven't looked at it much.
