### ISSUE TITLE
Get Medias by username

### ISSUE THREAD

**Issue by arislanhaikal** [suphiyasin/instagram-api#4]
Hi, 
I need some help to get medias
I try to get user info with

`$api->webapi->getUserInfoFromUsername($token, $username);`

I see this user response include _edge_owner_to_timeline_media_
But no medias edges included and with response empty array

Is there a special function to retrieve media?

Thank for your awesome tools

**Comment by suphiyasin** [comment]
Hello, I will be home in a few hours, I will test and get back to you.

**Comment by suphiyasin** [comment]
Hello, I did a review. The response of the mentioned getUserInfoFromUsername function contains only information about the username.
If you want to receive media, you need to use the getFeed function from the mobile API.
example:
`
$api->user->getFeed(null, $userid);
`

**Comment by arislanhaikal** [comment]
Nice, 
What do you mean in _manuel_?

`$api->manuel->getFeed(null, $userid);`

This is only return the first 12 medias. Can it possible to get next page medias?

**Comment by suphiyasin** [comment]
There is next media id in the incoming response, you need to add it to the request. (copy and paste the function and edit the 2nd function)

**Comment by arislanhaikal** [comment]
Response getFeed function like this.
How do I move to the next page?

![CleanShot 2024-04-06 at 07 05 38](https://github.com/suphiyasin/instagram-api/assets/14258054/7c082cb5-38fa-4a76-baa6-92ce7778ebe0)

Can you elaborate function with example?

Sorry I ask many questions :)

**Comment by suphiyasin** [comment]
Hello, I am on holiday (it will last 1 week). After 1 week, write something here again and remind me, I will send you the new function.

**Comment by arislanhaikal** [comment]
Hi @suphiyasin, have you finished your holiday? I waiting for you

**Comment by suphiyasin** [comment]
Hello yes I am back, thank you for reminding me.
I didn't have a chance to test it, but this code should work.
```php
	public function getMoreMedia($userid = null, $nextmediaid){
		$userid = $userid ?? $this->userid;
		$url = $this->apibase.'/api/v1/feed/user/'.$userid.'/?exclude_comment=true&max_id='.$nextmediaid.'&only_fetch_first_carousel_media=false';
		$sendRequest = $this->getwithcookie($url, null);
		return $sendRequest;
	}
```
