### ISSUE TITLE
Two Factor Login Not Workin

### ISSUE THREAD

**Issue by NaveenNain1** [suphiyasin/instagram-api#5]
I am using this code:
I have to use 6-digit code:
But gives an error in response: {"message":"This code is no longer valid. Please request a new code.","status":"fail","error_type":"invalid_nonce"}

PLEASE CHECK I THINK THERE IS PROBLEM IN FUNCTION      
 $api = new Instagram();
    $username = 'mr_naveennain';
    $password = 'Vikram!126116';
if(isset($_GET['factorcode'])){
$twofid = $_GET['twoid'];
	//1= Sms Verifivation || 2 = backup codes || 3 = Duo app code || 4= I guess its whatsapp 
	$step3 = json_decode($api->login->twofactorv2($username, $twofid, $_GET["factorcode"], "3"), true);
	print_r($step3);
if($step3["status"] == "ok"){
echo "login success";
}else{
echo "login fail";
}
}else{
$step1 = json_decode($api->login->loginv2($username, $password), true);
if($step1["Status"] == "ok"){
echo "already logged";
}else if($step1["Status"] == "fail" and isset($step1["TwoFactorId"])){
	$twofid = $step1["TwoFactorId"];
	print_r($step1);
	echo '<form action="" method="GET"><input type="hidden" value="'.$step1["TwoFactorId"].'" name="twoid"/><input type="number" name="factorcode" palceholder="Enter the 6 digit code" /> <input type="submit"/></form>';
	
}else{
//somthing went wrong
	var_dump($step1);
}
}

**Comment by NaveenNain1** [comment]
Please check, I think there is a problem in this library

**Comment by suphiyasin** [comment]
Hello, the code you sent does not submit anywhere.

**Comment by suphiyasin** [comment]
Also please change your password.
```php
$username = 'mr_naveennain';
$password = 'Vikram!126116';

```

**Comment by NaveenNain1** [comment]
Brother please check the lib with you Instagram id & Password with 2FA.

**Comment by NaveenNain1** [comment]
can check
