### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by phillypro** [suphiyasin/instagram-api#7]
woiuld you be open to expanding asn existing python library ....the instagram private api library seems to be an abandoned project kind of....wanna take a shot at attaining livestream broadcast key

**Comment by suphiyasin** [comment]
Hello, Instagram is closed for 48+ hours in Turkey. If it opens, it is a subject that interests me. I would like to test it.

**Comment by suphiyasin** [comment]
Hello, I will not be able to take care of this work due to my busy schedule.
