### ISSUE TITLE
Story with stickers

### ISSUE THREAD

**Issue by bondobrus** [suphiyasin/instagram-api#9]
Hello will that be possible to add someday a way to publish story with vissible stickers example: link sticker 

![story](https://github.com/user-attachments/assets/5bb608d0-9df9-4079-b6d0-af862a3890ed)

**Comment by suphiyasin** [comment]
If my project is finished, I am thinking of adding stroy functions.

**Comment by bondobrus** [comment]
Fingers crossed! Thanks for immediate response.
